/**
 * extensionBridge.ts — Named-pipe server (daemon side).
 *
 * Listens on a randomised pipe path (ADR-10) supplied via PipeAuthConfig.
 * Each CLI extension instance connects, sends a `hello` message with an
 * authToken, and is tracked in a Map<sessionId, ExtensionConnection>.
 *
 * Protocol: UTF-8 JSON-Lines (one JSON object per newline-terminated line).
 *           Max 64 KB per line (ADR-3).
 *           Canonical message schema per ADR-8.
 *
 * Heartbeat: daemon sends `ping` every 30 s (ADR-7). Extension must reply
 *            `pong` within 5 s; if missed, a 15 s grace period begins.
 *            After grace expires without pong the session is marked
 *            unreachable and evicted. Normal pipe teardown is detected
 *            immediately via the `close` event (fast path, <1 s).
 *
 * ADR compliance: ADR-3 (single pipe), ADR-4 (crash = unreachable),
 *                 ADR-5 (user-level daemon), ADR-7 (ping/pong + teardown),
 *                 ADR-8 (canonical wire protocol: inject/stream/requestId).
 */

import { EventEmitter } from 'node:events';
import * as net from 'node:net';
import { randomUUID, timingSafeEqual } from 'node:crypto';
import type { PipeAuthConfig } from './pipeAuth.js';
import { cleanupPipeAuth } from './pipeAuth.js';

// ── Constants ────────────────────────────────────────────────────────────────

const HEARTBEAT_INTERVAL_MS = 30_000;
/** ADR-7: pong expected within this many ms after a ping is sent. */
const PONG_WINDOW_MS = 5_000;
/** ADR-7: grace period after missed pong before marking session unreachable. */
const GRACE_PERIOD_MS = 15_000;
/** ADR-3: max bytes per JSON-Lines frame (64 KB). */
const MAX_LINE_BYTES = 64 * 1024;

// ── Protocol message types ────────────────────────────────────────────────────
//
// Inbound (extension → daemon)

/** First message from every new extension connection (re-sent on reconnect per ADR-6). */
export interface RegisterMessage {
  type: 'hello';
  sessionId: string;
  /** Human-readable session label. Reads SESSION_NAME env var; falls back to sessionId. */
  sessionName: string;
  /** ADR-10: per-run CSPRNG token from bridge-auth.json. Required since B3. */
  authToken: string;
}

/** Heartbeat reply from extension. `id` must echo the ping's `id`. */
export interface PongMessage {
  type: 'pong';
  id: string;
  sessionId: string;
}

/** CLI session event forwarded from the extension to the daemon (reserved for forward compat). */
export interface SessionEventMessage {
  type: 'session.event';
  sessionId: string;
  payload: unknown;
}

/** One streaming chunk of a CLI response (extension → daemon). */
export interface StreamMessage {
  type: 'stream';
  sessionId: string;
  requestId: string;
  chunk: string;
  /** `true` on the final chunk for this requestId. Exactly one per request. */
  done: boolean;
}

/** Terminal error for a CLI response (extension → daemon). */
export interface StreamErrorMessage {
  type: 'stream.error';
  sessionId: string;
  requestId: string;
  error: string;
}

// ADR-9: three new control-plane messages (§3 wire schema).

/** Extension → daemon: destructive tool needs user approval before execution. */
export interface PermissionRequestMessage {
  type: 'permission.request';
  sessionId: string;
  /** Data-plane request the permission belongs to (context only; one request may produce multiple prompts). */
  requestId: string;
  /** UUID generated by the extension; used to correlate the daemon's response. */
  permissionId: string;
  toolName: string;
  /** JSON-serialised tool arguments, truncated to 4096 chars on the extension side. */
  args: string;
  riskLevel: 'destructive';
}

/** Extension → daemon: the extension has abandoned a pending permissionCallback. Daemon must clean up. */
export interface PermissionCancelledMessage {
  type: 'permission.cancelled';
  sessionId: string;
  permissionId: string;
}

export type InboundMessage =
  | RegisterMessage
  | PongMessage
  | SessionEventMessage
  | StreamMessage
  | StreamErrorMessage
  | PermissionRequestMessage
  | PermissionCancelledMessage;

//
// Outbound (daemon → extension)

/** Acknowledgement sent after successful `hello`. */
export interface RegisteredMessage {
  type: 'session.registered';
  sessionId: string;
}

/** Heartbeat probe. Extension must reply `pong` with the same `id`. */
export interface PingMessage {
  type: 'ping';
  id: string;
  sessionId: string;
}

/** Command injected into the CLI session by the daemon. */
export interface InjectMessage {
  type: 'inject';
  sessionId: string;
  requestId: string;
  text: string;
}

/** Daemon → extension: user's approval decision for a pending permission request. */
export interface PermissionResponseMessage {
  type: 'permission.response';
  sessionId: string;
  permissionId: string;
  decision: 'allow' | 'deny';
}

export type OutboundMessage =
  | RegisteredMessage
  | PingMessage
  | InjectMessage
  | PermissionResponseMessage;

// ── Connection state ─────────────────────────────────────────────────────────

/** Status of an extension session. */
export type ConnectionStatus = 'registered' | 'unreachable';

/** Public handle for a registered extension connection. */
export interface ExtensionConnection {
  readonly sessionId: string;
  readonly status: ConnectionStatus;
  /** Send a typed outbound message to this extension. */
  send(msg: OutboundMessage): void;
}

/** Internal implementation — includes mutable status and heartbeat bookkeeping. */
interface InternalConnection extends ExtensionConnection {
  status: ConnectionStatus;
  /** Human-readable session label supplied in the `hello` message (SESSION_NAME env var). */
  readonly sessionName: string;
  readonly socket: net.Socket;
  /** ID of the ping we're waiting on, or undefined if no outstanding ping. */
  pendingPingId: string | undefined;
  pongTimeoutHandle: ReturnType<typeof setTimeout> | undefined;
  graceTimeoutHandle: ReturnType<typeof setTimeout> | undefined;
}

// ── BridgeEmitter — typed event emitter (composition) ───────────────────────

/**
 * Typed event subscription handle for ExtensionBridge.
 *
 * Events:
 * - `session.registered`   — extension connected and sent hello
 * - `session.disconnected` — pipe closed or heartbeat timed out (session evicted)
 * - `session.event`        — CLI event forwarded by the extension (reserved, future use)
 * - `stream`               — one streaming chunk from a CLI response
 * - `stream.error`         — terminal error for a CLI response
 * - `permission.request`   — destructive tool needs user approval (ADR-9)
 * - `permission.cancelled` — extension abandoned a pending permission (ADR-9)
 */
export interface BridgeEmitter {
  on(event: 'session.registered', listener: (sessionId: string) => void): this;
  on(event: 'session.disconnected', listener: (sessionId: string) => void): this;
  on(event: 'session.event', listener: (sessionId: string, payload: unknown) => void): this;
  on(
    event: 'stream',
    listener: (sessionId: string, requestId: string, chunk: string, done: boolean) => void,
  ): this;
  on(
    event: 'stream.error',
    listener: (sessionId: string, requestId: string, error: string) => void,
  ): this;
  on(
    event: 'permission.request',
    listener: (
      sessionId: string,
      requestId: string,
      permissionId: string,
      toolName: string,
      args: string,
    ) => void,
  ): this;
  on(
    event: 'permission.cancelled',
    listener: (sessionId: string, permissionId: string) => void,
  ): this;
  off(event: string, listener: (...args: unknown[]) => void): this;
}

// ── ExtensionBridge ───────────────────────────────────────────────────────────

/**
 * Named-pipe server that multiplexes connections from Copilot CLI extension
 * processes. Implements BridgeEmitter for typed event subscriptions.
 */
export class ExtensionBridge implements BridgeEmitter {
  private readonly _emitter = new EventEmitter();
  private server: net.Server | null = null;
  /** Registered sessions, keyed by sessionId. */
  private readonly sessions = new Map<string, InternalConnection>();
  /** Sockets that have connected but not yet sent `register`. */
  private readonly pendingSockets = new Set<net.Socket>();
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null;

  constructor(private readonly _authConfig: PipeAuthConfig) {}

  // ── BridgeEmitter implementation ─────────────────────────────────────────

  on(event: 'session.registered', listener: (sessionId: string) => void): this;
  on(event: 'session.disconnected', listener: (sessionId: string) => void): this;
  on(event: 'session.event', listener: (sessionId: string, payload: unknown) => void): this;
  on(
    event: 'stream',
    listener: (sessionId: string, requestId: string, chunk: string, done: boolean) => void,
  ): this;
  on(
    event: 'stream.error',
    listener: (sessionId: string, requestId: string, error: string) => void,
  ): this;
  on(
    event: 'permission.request',
    listener: (
      sessionId: string,
      requestId: string,
      permissionId: string,
      toolName: string,
      args: string,
    ) => void,
  ): this;
  on(
    event: 'permission.cancelled',
    listener: (sessionId: string, permissionId: string) => void,
  ): this;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  on(event: string, listener: (...args: any[]) => void): this {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
    this._emitter.on(event, listener);
    return this;
  }

  off(event: string, listener: (...args: unknown[]) => void): this {
    this._emitter.off(event, listener as (...args: unknown[]) => void);
    return this;
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Start the named-pipe server.
   * Resolves when the server is listening and ready to accept connections.
   * No-op if already started.
   */
  start(): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      if (this.server !== null) {
        resolve();
        return;
      }

      const server = net.createServer((socket) => {
        this.handleConnection(socket);
      });

      server.once('error', (err) => {
        reject(err);
      });

      server.listen(this._authConfig.pipePath, () => {
        this.server = server;
        this.startHeartbeat();
        console.log(`[bridge] Listening on ${this._authConfig.pipePath}`);
        resolve();
      });
    });
  }

  /**
   * Gracefully stop the server, cancel all heartbeat timers, and destroy
   * every open socket. Resolves when the server is fully closed.
   */
  stop(): Promise<void> {
    this.stopHeartbeat();

    for (const conn of this.sessions.values()) {
      this.clearPingState(conn);
      conn.socket.destroy();
    }
    for (const socket of this.pendingSockets) {
      socket.destroy();
    }
    this.sessions.clear();
    this.pendingSockets.clear();

    // N2: remove the auth file so stale credentials don't linger after shutdown.
    void cleanupPipeAuth();

    return new Promise<void>((resolve) => {
      if (this.server === null) {
        resolve();
        return;
      }
      this.server.close(() => {
        this.server = null;
        resolve();
      });
    });
  }

  /**
   * Returns the public handle for a registered session, or `undefined`
   * if the session is not currently connected.
   */
  getSession(sessionId: string): ExtensionConnection | undefined {
    return this.sessions.get(sessionId);
  }

  /**
   * Look up a registered session by its human-readable name (the `sessionName`
   * field from the extension's `hello` message — typically the SESSION_NAME env var).
   * Returns `undefined` if no registered session has that name, or if the matching
   * session has become unreachable.
   */
  getSessionByName(sessionName: string): ExtensionConnection | undefined {
    for (const conn of this.sessions.values()) {
      if (conn.sessionName === sessionName && conn.status === 'registered') {
        return conn;
      }
    }
    return undefined;
  }

  /**
   * Inject a text command into an extension identified by `sessionId`.
   * Generates and returns a `requestId` for response correlation.
   * Returns `false` if the session is not registered or is unreachable.
   */
  sendCommand(sessionId: string, text: string): string | false {
    const conn = this.sessions.get(sessionId);
    if (conn === undefined || conn.status !== 'registered') return false;
    const requestId = randomUUID();
    conn.send({ type: 'inject', sessionId, requestId, text });
    return requestId;
  }

  /**
   * Send a `permission.response` to the extension for the given session.
   * No-op if the session is not registered or unreachable — the extension
   * will detect the pipe drop via its own close handler.
   */
  sendPermissionResponse(sessionId: string, permissionId: string, decision: 'allow' | 'deny'): void {
    const conn = this.sessions.get(sessionId);
    if (conn === undefined || conn.status !== 'registered') return;
    conn.send({ type: 'permission.response', sessionId, permissionId, decision });
  }

  // ── Connection lifecycle ────────────────────────────────────────────────────

  private handleConnection(socket: net.Socket): void {
    // Minor: cap pre-hello (pending) sockets to prevent slow-loris resource exhaustion.
    if (this.pendingSockets.size >= 10) {
      console.warn('[bridge] Pending socket limit (10) reached — rejecting new connection');
      socket.destroy();
      return;
    }

    this.pendingSockets.add(socket);

    // Minor: 10s auth timeout — if hello isn't received by then, close the socket.
    const authTimeout = setTimeout(() => {
      if (this.pendingSockets.has(socket)) {
        console.warn('[bridge] Auth timeout (10 s) — closing pre-hello socket');
        this.pendingSockets.delete(socket);
        socket.destroy();
      }
    }, 10_000);
    socket.once('close', () => { clearTimeout(authTimeout); });

    let lineBuffer = '';

    socket.setEncoding('utf-8');

    socket.on('data', (chunk: string) => {
      lineBuffer += chunk;

      // DoS guard: drop connections that send frames larger than 64 KB.
      if (lineBuffer.length > MAX_LINE_BYTES) {
        console.warn('[bridge] Inbound buffer exceeded 64 KB — closing connection');
        socket.destroy();
        return;
      }

      let newlineIdx: number;
      while ((newlineIdx = lineBuffer.indexOf('\n')) !== -1) {
        const line = lineBuffer.slice(0, newlineIdx).trim();
        lineBuffer = lineBuffer.slice(newlineIdx + 1);
        if (line.length > 0) {
          this.handleLine(socket, line);
        }
      }
    });

    socket.on('close', () => {
      this.pendingSockets.delete(socket);

      for (const [sessionId, conn] of this.sessions) {
        if (conn.socket === socket) {
          this.clearPingState(conn);
          this.sessions.delete(sessionId);
          console.log(`[bridge] Session disconnected (pipe close): ${sessionId}`);
          this._emitter.emit('session.disconnected', sessionId);
          break;
        }
      }
    });

    socket.on('error', (err) => {
      // 'close' fires after 'error'; cleanup is handled in the close handler.
      console.warn('[bridge] Socket error:', err.message);
    });
  }

  // ── Message dispatch ────────────────────────────────────────────────────────

  private handleLine(socket: net.Socket, line: string): void {
    let msg: unknown;
    try {
      msg = JSON.parse(line);
    } catch {
      console.warn('[bridge] Non-JSON line received — ignoring');
      return;
    }

    if (typeof msg !== 'object' || msg === null || !('type' in msg)) {
      console.warn('[bridge] Malformed message (missing type field) — ignoring');
      return;
    }

    const type = (msg as Record<string, unknown>)['type'];
    const conn = this.findConnectionBySocket(socket);

    switch (type) {
      case 'hello':
        this.handleHello(socket, msg as RegisterMessage);
        break;
      case 'pong':
        if (conn !== undefined) this.handlePong(conn, msg as PongMessage);
        break;
      case 'session.event':
        if (conn !== undefined) {
          this._emitter.emit('session.event', conn.sessionId, (msg as SessionEventMessage).payload);
        }
        break;
      case 'stream': {
        if (conn !== undefined) {
          const sm = msg as StreamMessage;
          this._emitter.emit('stream', conn.sessionId, sm.requestId, sm.chunk, sm.done);
        }
        break;
      }
      case 'stream.error': {
        if (conn !== undefined) {
          const se = msg as StreamErrorMessage;
          this._emitter.emit('stream.error', conn.sessionId, se.requestId, se.error);
        }
        break;
      }
      case 'permission.request': {
        if (conn !== undefined) {
          const pr = msg as PermissionRequestMessage;
          if (
            typeof pr.permissionId === 'string' && pr.permissionId.length > 0 &&
            typeof pr.toolName === 'string' && pr.toolName.length > 0 &&
            pr.riskLevel === 'destructive'
          ) {
            this._emitter.emit(
              'permission.request',
              conn.sessionId,
              pr.requestId,
              pr.permissionId,
              pr.toolName,
              pr.args ?? '',
            );
          } else {
            console.warn('[bridge] permission.request: invalid fields — dropping');
          }
        }
        break;
      }
      case 'permission.cancelled': {
        if (conn !== undefined) {
          const pc = msg as PermissionCancelledMessage;
          if (typeof pc.permissionId === 'string' && pc.permissionId.length > 0) {
            this._emitter.emit('permission.cancelled', conn.sessionId, pc.permissionId);
          } else {
            console.warn('[bridge] permission.cancelled: missing permissionId — dropping');
          }
        }
        break;
      }
      default:
        console.warn(`[bridge] Unknown message type "${String(type)}" — ignoring`);
    }
  }

  private handleHello(socket: net.Socket, msg: RegisterMessage): void {
    const { sessionId } = msg;

    if (typeof sessionId !== 'string' || sessionId.length === 0) {
      console.warn('[bridge] register message missing sessionId — closing connection');
      socket.destroy();
      return;
    }

    // ADR-10 Option A: validate auth token before any session interaction.
    // Use timingSafeEqual to defend against timing side-channels.
    // Close without sending an error frame to avoid acting as an oracle.
    const provided = typeof msg.authToken === 'string'
      ? Buffer.from(msg.authToken, 'utf8')
      : Buffer.alloc(0);
    const expected = Buffer.from(this._authConfig.token, 'utf8');
    if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) {
      console.warn('[bridge] Auth token mismatch — closing unauthenticated connection');
      socket.destroy();
      return;
    }

    // I6: reject duplicate sessionName claimed by a different sessionId.
    // Allows the same sessionId to reconnect (ADR-6 hello-resend rule).
    const existingByName = this.getSessionByName(msg.sessionName);
    if (existingByName !== undefined && existingByName.sessionId !== sessionId) {
      console.warn(
        `[bridge] Rejected hello: sessionName "${msg.sessionName}" already claimed by ` +
        `${existingByName.sessionId} — closing duplicate`,
      );
      socket.destroy();
      return;
    }

    // Evict any stale connection for the same sessionId (extension reconnected
    // after daemon restart per ADR-6 backoff policy; re-sends hello on reconnect).
    const stale = this.sessions.get(sessionId);
    if (stale !== undefined && stale.socket !== socket) {
      console.log(`[bridge] Replacing stale connection for session ${sessionId}`);
      this.clearPingState(stale);
      stale.socket.destroy();
    }

    const conn: InternalConnection = {
      sessionId,
      sessionName: msg.sessionName,
      socket,
      status: 'registered',
      pendingPingId: undefined,
      pongTimeoutHandle: undefined,
      graceTimeoutHandle: undefined,
      send: (outMsg: OutboundMessage) => {
        const frame = JSON.stringify(outMsg) + '\n';
        socket.write(frame, 'utf-8', (err?: Error | null) => {
          if (err) {
            console.warn(`[bridge] Write error for session ${sessionId}:`, err.message);
          }
        });
      },
    };

    this.pendingSockets.delete(socket);
    this.sessions.set(sessionId, conn);

    conn.send({ type: 'session.registered', sessionId });
    console.log(`[bridge] Session registered: ${sessionId}`);
    this._emitter.emit('session.registered', sessionId);
  }

  private handlePong(conn: InternalConnection, msg: PongMessage): void {
    if (conn.pendingPingId !== undefined && conn.pendingPingId === msg.id) {
      this.clearPingState(conn);
      if (conn.status === 'unreachable') {
        // unreachable: the session is deleted from this.sessions before the grace period
        // expires (sendPing → graceTimeout → sessions.delete → socket.destroy), so
        // findConnectionBySocket returns undefined and handlePong is never called with
        // a connection in 'unreachable' state. Branch retained for future-safety only.
        conn.status = 'registered';
        console.log(`[bridge] Session recovered (late pong): ${conn.sessionId}`);
      }
    }
  }

  // ── Heartbeat ────────────────────────────────────────────────────────────────

  private startHeartbeat(): void {
    this.heartbeatTimer = setInterval(() => {
      for (const conn of this.sessions.values()) {
        if (conn.status === 'registered') {
          this.sendPing(conn);
        }
      }
    }, HEARTBEAT_INTERVAL_MS);
  }

  private sendPing(conn: InternalConnection): void {
    // Clear any previous outstanding ping before sending a new one.
    this.clearPingState(conn);

    const id = randomUUID();
    conn.pendingPingId = id;
    conn.send({ type: 'ping', id, sessionId: conn.sessionId });

    // ADR-7: pong window (5 s), then grace period (15 s).
    conn.pongTimeoutHandle = setTimeout(() => {
      conn.pongTimeoutHandle = undefined;

      conn.graceTimeoutHandle = setTimeout(() => {
        conn.graceTimeoutHandle = undefined;
        // Only evict if this is still the outstanding ping (no late pong arrived).
        if (conn.pendingPingId === id) {
          conn.pendingPingId = undefined;
          conn.status = 'unreachable';
          console.warn(`[bridge] Session unreachable (missed pong): ${conn.sessionId}`);
          this.sessions.delete(conn.sessionId);
          conn.socket.destroy();
          this._emitter.emit('session.disconnected', conn.sessionId);
        }
      }, GRACE_PERIOD_MS);
    }, PONG_WINDOW_MS);
  }

  private stopHeartbeat(): void {
    if (this.heartbeatTimer !== null) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
  }

  // ── Utilities ────────────────────────────────────────────────────────────────

  private findConnectionBySocket(socket: net.Socket): InternalConnection | undefined {
    for (const conn of this.sessions.values()) {
      if (conn.socket === socket) return conn;
    }
    return undefined;
  }

  private clearPingState(conn: InternalConnection): void {
    if (conn.pongTimeoutHandle !== undefined) {
      clearTimeout(conn.pongTimeoutHandle);
      conn.pongTimeoutHandle = undefined;
    }
    if (conn.graceTimeoutHandle !== undefined) {
      clearTimeout(conn.graceTimeoutHandle);
      conn.graceTimeoutHandle = undefined;
    }
    conn.pendingPingId = undefined;
  }
}
