/**
 * protocol.ts — Wire-protocol type definitions for the extension ↔ daemon bridge.
 *
 * Extracted from extensionBridge.ts (ADR-8, ADR-9, ADR-11).
 * Transport/runtime code lives in extensionBridge.ts; only message shapes and
 * union types belong here.
 *
 * Consumers: extensionBridge.ts (re-exports for backwards-compat), afkMode.ts,
 * and any module that needs ModeState without importing the full bridge class.
 */

// ── Inbound (extension → daemon) ─────────────────────────────────────────────

/** First message from every new extension connection (re-sent on reconnect per ADR-6). */
export interface RegisterMessage {
  type: 'hello';
  sessionId: string;
  /** Human-readable session label. Reads SESSION_NAME env var; falls back to sessionId. */
  sessionName: string;
  /**
   * Working directory of the CLI session.
   * @required since ADR-11; legacy clients may omit; daemon falls back to its own cwd.
   */
  cwd?: string;
  /** ADR-10: per-run CSPRNG token from bridge-auth.json. Required since B3. */
  authToken: string;
}

/** Heartbeat reply from extension. `id` must echo the ping's `id`. */
export interface PongMessage {
  type: 'pong';
  id: string;
  sessionId: string;
}

/** CLI session event forwarded from the extension to the daemon (reserved for forward compat). */
export interface SessionEventMessage {
  type: 'session.event';
  sessionId: string;
  payload: unknown;
}

/** One streaming chunk of a CLI response (extension → daemon). */
export interface StreamMessage {
  type: 'stream';
  sessionId: string;
  requestId: string;
  chunk: string;
  /** `true` on the final chunk for this requestId. Exactly one per request. */
  done: boolean;
}

/** Terminal error for a CLI response (extension → daemon). */
export interface StreamErrorMessage {
  type: 'stream.error';
  sessionId: string;
  requestId: string;
  error: string;
}

// ADR-9: three new control-plane messages (§3 wire schema).

/** Extension → daemon: destructive tool needs user approval before execution. */
export interface PermissionRequestMessage {
  type: 'permission.request';
  sessionId: string;
  /** Data-plane request the permission belongs to (context only; one request may produce multiple prompts). */
  requestId: string;
  /** UUID generated by the extension; used to correlate the daemon's response. */
  permissionId: string;
  toolName: string;
  /** JSON-serialised tool arguments, truncated to 4096 chars on the extension side. */
  args: string;
  riskLevel: 'destructive';
}

/** Extension → daemon: the extension has abandoned a pending permissionCallback. Daemon must clean up. */
export interface PermissionCancelledMessage {
  type: 'permission.cancelled';
  sessionId: string;
  permissionId: string;
}

/** Extension → daemon: user requested machine-wide AFK mode from this CLI session. */
export interface AfkRequestMessage {
  type: 'afk.request';
  sessionId: string;
}

/** Extension → daemon: user requested machine-wide back-at-desk mode from this CLI session. */
export interface BackRequestMessage {
  type: 'back.request';
  sessionId: string;
}

export type InboundMessage =
  | RegisterMessage
  | PongMessage
  | SessionEventMessage
  | StreamMessage
  | StreamErrorMessage
  | PermissionRequestMessage
  | PermissionCancelledMessage
  | AfkRequestMessage
  | BackRequestMessage;

// ── Outbound (daemon → extension) ────────────────────────────────────────────

export interface ModeState {
  active: boolean;
  since: string;
}

/** Public wire-adjacent summary of a registered bridge session. */
export interface BridgeSessionInfo {
  readonly sessionId: string;
  readonly sessionName: string;
  readonly cwd: string;
}

/** Optional daemon-side registration fields added to the `session.registered` acknowledgement. */
export interface RegistrationExtras {
  mode?: ModeState;
  topicId?: number;
}

/** Hook for daemon features that augment the registration acknowledgement. */
export type RegistrationAugmenter = (session: BridgeSessionInfo) => Promise<RegistrationExtras>;

/** Acknowledgement sent after successful `hello`. */
export interface RegisteredMessage {
  type: 'session.registered';
  sessionId: string;
  mode?: ModeState;
  topicId?: number;
}

/** Heartbeat probe. Extension must reply `pong` with the same `id`. */
export interface PingMessage {
  type: 'ping';
  id: string;
  sessionId: string;
}

/** Command injected into the CLI session by the daemon. */
export interface InjectMessage {
  type: 'inject';
  sessionId: string;
  requestId: string;
  text: string;
}

/** Daemon → extension: user's approval decision for a pending permission request. */
export interface PermissionResponseMessage {
  type: 'permission.response';
  sessionId: string;
  permissionId: string;
  decision: 'allow' | 'deny';
}

/** Daemon → extension: the session has an active Telegram topic for AFK mode. */
export interface AfkActivatedMessage {
  type: 'afk.activated';
  sessionId: string;
  topicId: number;
  topicUrl: string;
}

/** Daemon → extension: this session is back at the desk. */
export interface BackConfirmedMessage {
  type: 'back.confirmed';
  sessionId: string;
}

/** Daemon → all extensions: machine-wide AFK mode changed. */
export interface ModeChangedMessage extends ModeState {
  type: 'mode.changed';
}

/** Daemon → extension: Telegram user text to mirror into the CLI session. */
export interface MirrorInputMessage {
  type: 'mirror.input';
  sessionId: string;
  text: string;
  source: 'telegram';
  topicId: number;
}

// DEFERRED (Phase 8): no daemon producer — envelope reserved for /clear and future relay commands per ADR-11 §9.
/** Daemon → extension: slash-command relay envelope; execution is deferred. */
export interface RelayCommandMessage {
  type: 'relay.command';
  sessionId: string;
  command: string;
  args: string[];
}

/**
 * Well-known daemon → extension error codes.
 *
 * The protocol keeps `ErrorMessage.code` as an open string so producers can add
 * advisory codes without breaking older consumers; use these constants when you
 * want narrowing or typo resistance for codes known to this package.
 */
export const ERROR_CODES = {
  AFK_ACTIVATION_FAILED: 'afk.activation_failed',
  AFK_NOT_ACTIVE: 'afk.not_active',
} as const;

/** Daemon → extension: an operation failed; the extension should surface the error to the user. */
export interface ErrorMessage {
  type: 'error';
  sessionId: string;
  error: string;
  /**
   * Machine-readable advisory error code.
   * See `ERROR_CODES` for well-known values; advisory only — the extension does not branch on this.
   */
  code?: string;
}

export type OutboundMessage =
  | RegisteredMessage
  | PingMessage
  | InjectMessage
  | PermissionResponseMessage
  | AfkActivatedMessage
  | BackConfirmedMessage
  | ModeChangedMessage
  | MirrorInputMessage
  | RelayCommandMessage
  | ErrorMessage;
